version: "3.9"

services:
  web:
    build: .
    command: pytest tests  # Run tests when the container starts
    depends_on:
      - mongo-test
    environment:
      - MONGO_URI=mongodb://mongo-test:27018/test_database
    volumes:
      - .:/app

  mongo-test:  # Separate MongoDB for tests
    image: mongo:latest
    ports:
      - "27018:27017"
